### ISSUE TITLE
文字超出显示三点省略号的方案ellipsis(单行，多行)

### ISSUE THREAD

**Issue by ZhengXingchi** [ZhengXingchi/ZhengXingchi.github.io#77]
# 关于单行
```
div {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Comment by ZhengXingchi** [comment]
# 多行就群龙混杂了
## -webkit-line-clamp 实现
```
div {
  display: -webkit-box;
  overflow: hidden;  
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```

## float 特性实现多行文本截断

缺点，因为我们是模拟省略号，所以显示位置有时候没办法刚刚好，所以可以考虑：

加一个渐变效果，贴合文字，就像上述 demo 效果一样。
添加 word-break:break-all; 使一个单词能够在换行时进行拆分，这样文字和省略号贴合效果更佳。

**Comment by ZhengXingchi** [comment]
# 参考文献  

[纯 CSS 实现多行文字截断](https://github.com/happylindz/blog/issues/12)

[纯 CSS 实现多行文字截断](https://zhuanlan.zhihu.com/p/34326190)

**Comment by ZhengXingchi** [comment]
因为UI设计师不希望文字截断的时候截断一半或者采用渐变来模糊这种效果的话，只能去寻找js有没有什么方法

**Comment by ZhengXingchi** [comment]
# 参考文献
[多行文本溢出显示省略号(…)全攻略](https://www.html.cn/archives/5206/)

[josephschmitt/Clamp.js](https://github.com/josephschmitt/Clamp.js)

**Comment by ZhengXingchi** [comment]
但是这个插件是js写的，笔者想找一款在react中能良好使用的插件。然后搜到了[react-string-clamp](https://www.npmjs.com/package/react-string-clamp),引入后发现无法使用，具体原因未知。

接着找到了[react-multi-clamp](https://developer.aliyun.com/mirror/npm/package/react-multi-clamp/v/1.0.0-beta.0)使用效果不错，这是根据[multi-clamp](https://github.com/jackyr/multi-clamp/blob/master/MultiClamp.js)进行改写的


同时还搜索到其它一些，留待以后备用
[react-clamp-lines](https://gitee.com/mirrors/react-clamp-lines)

[react-string-truncate](https://developer.aliyun.com/mirror/npm/package/react-string-truncate)

[react-clamp](https://www.npmjs.com/package/react-clamp)

**Comment by ZhengXingchi** [comment]
# 关于react-multi-clamp的bug
详见[the react-multi-clamp@2.0.1 donot work when ellipsis is a reactelement](https://github.com/jackyr/react-multi-clamp/issues/5)
解决方案为
```
   function doNotNeedToClamp(isForcePrevent) {
        
        if (!isForcePrevent) self.option.onClampStart.call(self, {
          needClamp: false
        });
        self.option.onClampEnd.call(self, {
          didClamp: false
        });
         
        self.element.appendChild(self.ellipsis );
        self.element.removeChild(self.ellipsis )
      }
    },
```

或者将self.element.style的display设置为none

**Comment by jackyr** [comment]
@ZhengXingchi 你好，react-multi-clamp的bug在`react-multi-clamp@2.0.2`版本已经修复。
那个解决方案有导致其他问题的风险，最好不要使用。

**Comment by ZhengXingchi** [comment]
@jackyr    谢谢作者的反馈，已更正。
